=begin comment

API2Cart OpenAPI

API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::BridgeApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# bridge_delete
#
# bridge.delete
#
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'bridge_delete' } = {
        summary => 'bridge.delete',
        params => $params,
        returns => 'AttributeValueDelete200Response',
        };
}
# @return AttributeValueDelete200Response
#
sub bridge_delete {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/bridge.delete.json';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(StoreKeyAuth ApiKeyAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('AttributeValueDelete200Response', $response);
    return $_response_object;
}

#
# bridge_download
#
# bridge.download
#
# @param boolean $whitelabel Identifies if there is a necessity to download whitelabel bridge. (optional, default to false)
{
    my $params = {
    'whitelabel' => {
        data_type => 'boolean',
        description => 'Identifies if there is a necessity to download whitelabel bridge.',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'bridge_download' } = {
        summary => 'bridge.download',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub bridge_download {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/bridge.download.file';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/zip');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'whitelabel'}) {
        $query_params->{'whitelabel'} = $self->{api_client}->to_query_value($args{'whitelabel'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(StoreKeyAuth ApiKeyAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# bridge_update
#
# bridge.update
#
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'bridge_update' } = {
        summary => 'bridge.update',
        params => $params,
        returns => 'AttributeUpdate200Response',
        };
}
# @return AttributeUpdate200Response
#
sub bridge_update {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/bridge.update.json';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(StoreKeyAuth ApiKeyAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('AttributeUpdate200Response', $response);
    return $_response_object;
}

1;
