=begin comment

API2Cart OpenAPI

API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::BatchApi');

my $api = WWW::OpenAPIClient::BatchApi->new();
isa_ok($api, 'WWW::OpenAPIClient::BatchApi');

#
# batch_job_list test
#
# uncomment below and update the test
#my $batch_job_list_count = undef; # replace NULL with a proper value
#my $batch_job_list_page_cursor = undef; # replace NULL with a proper value
#my $batch_job_list_ids = undef; # replace NULL with a proper value
#my $batch_job_list_created_from = undef; # replace NULL with a proper value
#my $batch_job_list_created_to = undef; # replace NULL with a proper value
#my $batch_job_list_processed_from = undef; # replace NULL with a proper value
#my $batch_job_list_processed_to = undef; # replace NULL with a proper value
#my $batch_job_list_response_fields = undef; # replace NULL with a proper value
#my $batch_job_list_result = $api->batch_job_list(count => $batch_job_list_count, page_cursor => $batch_job_list_page_cursor, ids => $batch_job_list_ids, created_from => $batch_job_list_created_from, created_to => $batch_job_list_created_to, processed_from => $batch_job_list_processed_from, processed_to => $batch_job_list_processed_to, response_fields => $batch_job_list_response_fields);

#
# batch_job_result test
#
# uncomment below and update the test
#my $batch_job_result_id = undef; # replace NULL with a proper value
#my $batch_job_result_result = $api->batch_job_result(id => $batch_job_result_id);


done_testing();
