=begin comment

API2Cart OpenAPI

API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::WebhookApi');

my $api = WWW::OpenAPIClient::WebhookApi->new();
isa_ok($api, 'WWW::OpenAPIClient::WebhookApi');

#
# webhook_count test
#
# uncomment below and update the test
#my $webhook_count_entity = undef; # replace NULL with a proper value
#my $webhook_count_action = undef; # replace NULL with a proper value
#my $webhook_count_active = undef; # replace NULL with a proper value
#my $webhook_count_result = $api->webhook_count(entity => $webhook_count_entity, action => $webhook_count_action, active => $webhook_count_active);

#
# webhook_create test
#
# uncomment below and update the test
#my $webhook_create_entity = undef; # replace NULL with a proper value
#my $webhook_create_action = undef; # replace NULL with a proper value
#my $webhook_create_callback = undef; # replace NULL with a proper value
#my $webhook_create_label = undef; # replace NULL with a proper value
#my $webhook_create_fields = undef; # replace NULL with a proper value
#my $webhook_create_active = undef; # replace NULL with a proper value
#my $webhook_create_store_id = undef; # replace NULL with a proper value
#my $webhook_create_result = $api->webhook_create(entity => $webhook_create_entity, action => $webhook_create_action, callback => $webhook_create_callback, label => $webhook_create_label, fields => $webhook_create_fields, active => $webhook_create_active, store_id => $webhook_create_store_id);

#
# webhook_delete test
#
# uncomment below and update the test
#my $webhook_delete_id = undef; # replace NULL with a proper value
#my $webhook_delete_result = $api->webhook_delete(id => $webhook_delete_id);

#
# webhook_events test
#
# uncomment below and update the test
#my $webhook_events_result = $api->webhook_events();

#
# webhook_list test
#
# uncomment below and update the test
#my $webhook_list_params = undef; # replace NULL with a proper value
#my $webhook_list_start = undef; # replace NULL with a proper value
#my $webhook_list_count = undef; # replace NULL with a proper value
#my $webhook_list_entity = undef; # replace NULL with a proper value
#my $webhook_list_action = undef; # replace NULL with a proper value
#my $webhook_list_active = undef; # replace NULL with a proper value
#my $webhook_list_ids = undef; # replace NULL with a proper value
#my $webhook_list_result = $api->webhook_list(params => $webhook_list_params, start => $webhook_list_start, count => $webhook_list_count, entity => $webhook_list_entity, action => $webhook_list_action, active => $webhook_list_active, ids => $webhook_list_ids);

#
# webhook_update test
#
# uncomment below and update the test
#my $webhook_update_id = undef; # replace NULL with a proper value
#my $webhook_update_callback = undef; # replace NULL with a proper value
#my $webhook_update_label = undef; # replace NULL with a proper value
#my $webhook_update_fields = undef; # replace NULL with a proper value
#my $webhook_update_active = undef; # replace NULL with a proper value
#my $webhook_update_result = $api->webhook_update(id => $webhook_update_id, callback => $webhook_update_callback, label => $webhook_update_label, fields => $webhook_update_fields, active => $webhook_update_active);


done_testing();
