=begin comment

API2Cart OpenAPI

API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::Object::CustomerAddAddressInner;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

API2Cart OpenAPI

API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "WWW::OpenAPIClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'CustomerAddAddressInner',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'address_book_type' => {
        datatype => 'string',
        base_name => 'address_book_type',
        description => 'Specifies customer&#39;s address type',
        format => '',
        read_only => '',
            },
    'address_book_first_name' => {
        datatype => 'string',
        base_name => 'address_book_first_name',
        description => 'Specifies customer&#39;s first name in the address book',
        format => '',
        read_only => '',
            },
    'address_book_last_name' => {
        datatype => 'string',
        base_name => 'address_book_last_name',
        description => 'Specifies customer&#39;s last name in the address book',
        format => '',
        read_only => '',
            },
    'address_book_company' => {
        datatype => 'string',
        base_name => 'address_book_company',
        description => 'Specifies customer&#39;s company name in the address book',
        format => '',
        read_only => '',
            },
    'address_book_fax' => {
        datatype => 'string',
        base_name => 'address_book_fax',
        description => 'Specifies customer&#39;s fax in the address book',
        format => '',
        read_only => '',
            },
    'address_book_phone' => {
        datatype => 'string',
        base_name => 'address_book_phone',
        description => 'Specifies customer&#39;s phone number in the address book',
        format => '',
        read_only => '',
            },
    'address_book_phone_mobile' => {
        datatype => 'string',
        base_name => 'address_book_phone_mobile',
        description => 'Specifies customer&#39;s mobile phone number in the address book',
        format => '',
        read_only => '',
            },
    'address_book_website' => {
        datatype => 'string',
        base_name => 'address_book_website',
        description => 'Specifies customer&#39;s website in the address book',
        format => '',
        read_only => '',
            },
    'address_book_address1' => {
        datatype => 'string',
        base_name => 'address_book_address1',
        description => 'Specifies customer&#39;s first address in the address book',
        format => '',
        read_only => '',
            },
    'address_book_address2' => {
        datatype => 'string',
        base_name => 'address_book_address2',
        description => 'Specifies customer&#39;s second address in the address book',
        format => '',
        read_only => '',
            },
    'address_book_city' => {
        datatype => 'string',
        base_name => 'address_book_city',
        description => 'Specifies customer&#39;s city in the address book',
        format => '',
        read_only => '',
            },
    'address_book_country' => {
        datatype => 'string',
        base_name => 'address_book_country',
        description => 'ISO code or name of country',
        format => '',
        read_only => '',
            },
    'address_book_state' => {
        datatype => 'string',
        base_name => 'address_book_state',
        description => 'ISO code or name of state.',
        format => '',
        read_only => '',
            },
    'address_book_postcode' => {
        datatype => 'string',
        base_name => 'address_book_postcode',
        description => 'Specifies customer&#39;s postcode',
        format => '',
        read_only => '',
            },
    'address_book_gender' => {
        datatype => 'string',
        base_name => 'address_book_gender',
        description => 'Specifies customer&#39;s gender',
        format => '',
        read_only => '',
            },
    'address_book_region' => {
        datatype => 'string',
        base_name => 'address_book_region',
        description => 'Specifies customer&#39;s region',
        format => '',
        read_only => '',
            },
    'address_book_default' => {
        datatype => 'boolean',
        base_name => 'address_book_default',
        description => 'Defines whether the address is used by default',
        format => '',
        read_only => '',
            },
    'address_book_tax_id' => {
        datatype => 'string',
        base_name => 'address_book_tax_id',
        description => 'Add Tax Id',
        format => '',
        read_only => '',
            },
    'address_book_identification_number' => {
        datatype => 'string',
        base_name => 'address_book_identification_number',
        description => 'The national ID card number of this person, or a unique tax identification number.',
        format => '',
        read_only => '',
            },
    'address_book_alias' => {
        datatype => 'string',
        base_name => 'address_book_alias',
        description => 'Specifies customer&#39;s alias in the address book',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'address_book_type' => 'string',
    'address_book_first_name' => 'string',
    'address_book_last_name' => 'string',
    'address_book_company' => 'string',
    'address_book_fax' => 'string',
    'address_book_phone' => 'string',
    'address_book_phone_mobile' => 'string',
    'address_book_website' => 'string',
    'address_book_address1' => 'string',
    'address_book_address2' => 'string',
    'address_book_city' => 'string',
    'address_book_country' => 'string',
    'address_book_state' => 'string',
    'address_book_postcode' => 'string',
    'address_book_gender' => 'string',
    'address_book_region' => 'string',
    'address_book_default' => 'boolean',
    'address_book_tax_id' => 'string',
    'address_book_identification_number' => 'string',
    'address_book_alias' => 'string'
} );

__PACKAGE__->attribute_map( {
    'address_book_type' => 'address_book_type',
    'address_book_first_name' => 'address_book_first_name',
    'address_book_last_name' => 'address_book_last_name',
    'address_book_company' => 'address_book_company',
    'address_book_fax' => 'address_book_fax',
    'address_book_phone' => 'address_book_phone',
    'address_book_phone_mobile' => 'address_book_phone_mobile',
    'address_book_website' => 'address_book_website',
    'address_book_address1' => 'address_book_address1',
    'address_book_address2' => 'address_book_address2',
    'address_book_city' => 'address_book_city',
    'address_book_country' => 'address_book_country',
    'address_book_state' => 'address_book_state',
    'address_book_postcode' => 'address_book_postcode',
    'address_book_gender' => 'address_book_gender',
    'address_book_region' => 'address_book_region',
    'address_book_default' => 'address_book_default',
    'address_book_tax_id' => 'address_book_tax_id',
    'address_book_identification_number' => 'address_book_identification_number',
    'address_book_alias' => 'address_book_alias'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
