=begin comment

API2Cart OpenAPI

API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::Object::OrderCalculate;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use WWW::OpenAPIClient::Object::OrderCalculateOrderItemInner;

use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

API2Cart OpenAPI

API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "WWW::OpenAPIClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'OrderCalculate',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'customer_email' => {
        datatype => 'string',
        base_name => 'customer_email',
        description => 'Defines the customer specified by email for whom the order needs to be calculated',
        format => '',
        read_only => '',
            },
    'currency_id' => {
        datatype => 'string',
        base_name => 'currency_id',
        description => 'Currency Id',
        format => '',
        read_only => '',
            },
    'store_id' => {
        datatype => 'string',
        base_name => 'store_id',
        description => 'Store Id',
        format => '',
        read_only => '',
            },
    'coupons' => {
        datatype => 'ARRAY[string]',
        base_name => 'coupons',
        description => 'Coupons that will be applied to order. If the order isn&#39;t eligible for any given discount code or there is no discount with such a code it will be skipped during calculation',
        format => '',
        read_only => '',
            },
    'shipp_first_name' => {
        datatype => 'string',
        base_name => 'shipp_first_name',
        description => 'Specifies shipping first name',
        format => '',
        read_only => '',
            },
    'shipp_last_name' => {
        datatype => 'string',
        base_name => 'shipp_last_name',
        description => 'Specifies shipping last name',
        format => '',
        read_only => '',
            },
    'shipp_address_1' => {
        datatype => 'string',
        base_name => 'shipp_address_1',
        description => 'Specifies first shipping address',
        format => '',
        read_only => '',
            },
    'shipp_address_2' => {
        datatype => 'string',
        base_name => 'shipp_address_2',
        description => 'Specifies second address line of a shipping street address',
        format => '',
        read_only => '',
            },
    'shipp_city' => {
        datatype => 'string',
        base_name => 'shipp_city',
        description => 'Specifies shipping city',
        format => '',
        read_only => '',
            },
    'shipp_postcode' => {
        datatype => 'string',
        base_name => 'shipp_postcode',
        description => 'Specifies shipping postcode',
        format => '',
        read_only => '',
            },
    'shipp_state' => {
        datatype => 'string',
        base_name => 'shipp_state',
        description => 'Specifies shipping state code',
        format => '',
        read_only => '',
            },
    'shipp_country' => {
        datatype => 'string',
        base_name => 'shipp_country',
        description => 'Specifies shipping country code',
        format => '',
        read_only => '',
            },
    'shipp_company' => {
        datatype => 'string',
        base_name => 'shipp_company',
        description => 'Specifies shipping company',
        format => '',
        read_only => '',
            },
    'shipp_phone' => {
        datatype => 'string',
        base_name => 'shipp_phone',
        description => 'Specifies shipping phone',
        format => '',
        read_only => '',
            },
    'bill_first_name' => {
        datatype => 'string',
        base_name => 'bill_first_name',
        description => 'Specifies billing first name',
        format => '',
        read_only => '',
            },
    'bill_last_name' => {
        datatype => 'string',
        base_name => 'bill_last_name',
        description => 'Specifies billing last name',
        format => '',
        read_only => '',
            },
    'bill_address_1' => {
        datatype => 'string',
        base_name => 'bill_address_1',
        description => 'Specifies first billing address',
        format => '',
        read_only => '',
            },
    'bill_address_2' => {
        datatype => 'string',
        base_name => 'bill_address_2',
        description => 'Specifies second billing address',
        format => '',
        read_only => '',
            },
    'bill_city' => {
        datatype => 'string',
        base_name => 'bill_city',
        description => 'Specifies billing city',
        format => '',
        read_only => '',
            },
    'bill_postcode' => {
        datatype => 'string',
        base_name => 'bill_postcode',
        description => 'Specifies billing postcode',
        format => '',
        read_only => '',
            },
    'bill_state' => {
        datatype => 'string',
        base_name => 'bill_state',
        description => 'Specifies billing state code',
        format => '',
        read_only => '',
            },
    'bill_country' => {
        datatype => 'string',
        base_name => 'bill_country',
        description => 'Specifies billing country code',
        format => '',
        read_only => '',
            },
    'bill_company' => {
        datatype => 'string',
        base_name => 'bill_company',
        description => 'Specifies billing company',
        format => '',
        read_only => '',
            },
    'bill_phone' => {
        datatype => 'string',
        base_name => 'bill_phone',
        description => 'Specifies billing phone',
        format => '',
        read_only => '',
            },
    'response_fields' => {
        datatype => 'string',
        base_name => 'response_fields',
        description => 'Set this parameter in order to choose which entity fields you want to retrieve',
        format => '',
        read_only => '',
            },
    'order_item' => {
        datatype => 'ARRAY[OrderCalculateOrderItemInner]',
        base_name => 'order_item',
        description => '',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'customer_email' => 'string',
    'currency_id' => 'string',
    'store_id' => 'string',
    'coupons' => 'ARRAY[string]',
    'shipp_first_name' => 'string',
    'shipp_last_name' => 'string',
    'shipp_address_1' => 'string',
    'shipp_address_2' => 'string',
    'shipp_city' => 'string',
    'shipp_postcode' => 'string',
    'shipp_state' => 'string',
    'shipp_country' => 'string',
    'shipp_company' => 'string',
    'shipp_phone' => 'string',
    'bill_first_name' => 'string',
    'bill_last_name' => 'string',
    'bill_address_1' => 'string',
    'bill_address_2' => 'string',
    'bill_city' => 'string',
    'bill_postcode' => 'string',
    'bill_state' => 'string',
    'bill_country' => 'string',
    'bill_company' => 'string',
    'bill_phone' => 'string',
    'response_fields' => 'string',
    'order_item' => 'ARRAY[OrderCalculateOrderItemInner]'
} );

__PACKAGE__->attribute_map( {
    'customer_email' => 'customer_email',
    'currency_id' => 'currency_id',
    'store_id' => 'store_id',
    'coupons' => 'coupons',
    'shipp_first_name' => 'shipp_first_name',
    'shipp_last_name' => 'shipp_last_name',
    'shipp_address_1' => 'shipp_address_1',
    'shipp_address_2' => 'shipp_address_2',
    'shipp_city' => 'shipp_city',
    'shipp_postcode' => 'shipp_postcode',
    'shipp_state' => 'shipp_state',
    'shipp_country' => 'shipp_country',
    'shipp_company' => 'shipp_company',
    'shipp_phone' => 'shipp_phone',
    'bill_first_name' => 'bill_first_name',
    'bill_last_name' => 'bill_last_name',
    'bill_address_1' => 'bill_address_1',
    'bill_address_2' => 'bill_address_2',
    'bill_city' => 'bill_city',
    'bill_postcode' => 'bill_postcode',
    'bill_state' => 'bill_state',
    'bill_country' => 'bill_country',
    'bill_company' => 'bill_company',
    'bill_phone' => 'bill_phone',
    'response_fields' => 'response_fields',
    'order_item' => 'order_item'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
