=begin comment

API2Cart OpenAPI

API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::Object::ProductImageAdd;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

API2Cart OpenAPI

API2Cart

The version of the OpenAPI document: 1.1
Contact: contact@api2cart.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "WWW::OpenAPIClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'ProductImageAdd',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'type' => {
        datatype => 'string',
        base_name => 'type',
        description => 'Defines image&#39;s types that are specified by comma-separated list',
        format => '',
        read_only => '',
            },
    'image_name' => {
        datatype => 'string',
        base_name => 'image_name',
        description => 'Defines image&#39;s name',
        format => '',
        read_only => '',
            },
    'product_id' => {
        datatype => 'string',
        base_name => 'product_id',
        description => 'Defines product id where the image should be added',
        format => '',
        read_only => '',
            },
    'product_variant_id' => {
        datatype => 'string',
        base_name => 'product_variant_id',
        description => 'Defines product&#39;s variants specified by variant id',
        format => '',
        read_only => '',
            },
    'variant_ids' => {
        datatype => 'string',
        base_name => 'variant_ids',
        description => 'Defines product&#39;s variants ids',
        format => '',
        read_only => '',
            },
    'option_value_ids' => {
        datatype => 'string',
        base_name => 'option_value_ids',
        description => 'Defines product&#39;s option values ids',
        format => '',
        read_only => '',
            },
    'store_id' => {
        datatype => 'string',
        base_name => 'store_id',
        description => 'Store Id',
        format => '',
        read_only => '',
            },
    'lang_id' => {
        datatype => 'string',
        base_name => 'lang_id',
        description => 'Add product image on specified language id',
        format => '',
        read_only => '',
            },
    'url' => {
        datatype => 'string',
        base_name => 'url',
        description => 'Defines URL of the image that has to be added',
        format => '',
        read_only => '',
            },
    'content' => {
        datatype => 'string',
        base_name => 'content',
        description => 'Content(body) encoded in base64 of image file',
        format => '',
        read_only => '',
            },
    'label' => {
        datatype => 'string',
        base_name => 'label',
        description => 'Defines alternative text that has to be attached to the picture',
        format => '',
        read_only => '',
            },
    'mime' => {
        datatype => 'string',
        base_name => 'mime',
        description => 'Mime type of image http://en.wikipedia.org/wiki/Internet_media_type.',
        format => '',
        read_only => '',
            },
    'position' => {
        datatype => 'int',
        base_name => 'position',
        description => 'Defines image’s position in the list',
        format => '',
        read_only => '',
            },
    'use_latest_api_version' => {
        datatype => 'boolean',
        base_name => 'use_latest_api_version',
        description => 'Use the latest platform API version',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'type' => 'string',
    'image_name' => 'string',
    'product_id' => 'string',
    'product_variant_id' => 'string',
    'variant_ids' => 'string',
    'option_value_ids' => 'string',
    'store_id' => 'string',
    'lang_id' => 'string',
    'url' => 'string',
    'content' => 'string',
    'label' => 'string',
    'mime' => 'string',
    'position' => 'int',
    'use_latest_api_version' => 'boolean'
} );

__PACKAGE__->attribute_map( {
    'type' => 'type',
    'image_name' => 'image_name',
    'product_id' => 'product_id',
    'product_variant_id' => 'product_variant_id',
    'variant_ids' => 'variant_ids',
    'option_value_ids' => 'option_value_ids',
    'store_id' => 'store_id',
    'lang_id' => 'lang_id',
    'url' => 'url',
    'content' => 'content',
    'label' => 'label',
    'mime' => 'mime',
    'position' => 'position',
    'use_latest_api_version' => 'use_latest_api_version'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
